#title in header
title: "Hi Everyone ğŸ‘‹"

#main info
#owner
owner: "I'm Caleb Ikhuohon"
info: "A software engineer passionate about distributed systems, cloud infra and systems programming"
#description
desc: "A space where I share learnings from my engineering & product journey: products, startups, distributed systems, devops, open-source, SRE, etc. ğŸ˜„"

#menu
menu:
  Blog: /Blog
  About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/calebikhuohon
linkedin: https://www.linkedin.com/in/caleb-ikhuohon-eboreime-5860a3a7/
twitter: https://twitter.com/calebikh

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: https-calebikhuohon-com
